In [ ]:
#1.구구단 테이블 만들기
# - 1. 2~9단 작성
# - 2. axis = 0(단) 열에 대한 작성(선호도 작성)
# - 3. ndarray 채택 : 열에대한 인덱싱 가능
#2.메뉴 작성
# - 1.한개의 단 출력
# - 2.단의 범위 출력
# - 3.종료
#3. 메뉴 상세 동작
# - 1. 한 개의 단 출력
#  - 사용자 입력을 받음 ( '단 번호 입력 : ') 
#  - 선태한 단을 위에서 아래로 출력(함수->printOneDan())
#  - 메뉴 표시
# - 2. 단의 범위 출력
#  - 사용자 입력을 받음 ( '단 번호 범위 입력 예) 3 5 ; ')
#  - 선택한 단을 위에서 아래로 출력 ( axis=0 -> printRangeDan())
#  - 메뉴 표시
# 3. 원하는 단 목록의 출력에 대한 입력은 다음과 같습니다.
#   - 출력을 원하는 단 목록 입력 예) 1 3 5 6 : 
#   - 출력 내용은 1,3,5,6 단이 됩니다.
#   - 동작 구현은 def doMenu3(): pass  함수로 작성합니다.
#   - doMenu3도 잘 동작되도록 myRun 도 수정합니다.
# - 3. 종료
#  - 프로그램 종료
import numpy as np

class  GuGuDan:
  
  def __init__(self,N): #구구단 초기화
    self.N=N
    self.GuGuTable=np.array( [    [    ''.join(f"{i}*{j}={i*j:<5}")  for i in range(2,N+1)]    for j in range(1,N+1)  ] )

  def Menu(self):# 메뉴
    print("-"*10,"MeNu","-"*10,
          "\n1.    한개의  단출력\n2.    단의 범위 출력\n3.    선택한 단 출력\n4.    종료\n",
          "-"*25)

  def printOneDan(self): ## 1번메뉴
    select=int(input("단수 단보기 => 번호 입력 (2~N의 숫자로입력)"))
    print(self.GuGuTable[:,[select-2]])

  def printRangeDan(self): ## 2번 메뉴
    x,y=map(int,input("단의 범위 보기 => 번호 입력 (2~N의 숫자로입력 : ex)2 5)").split())
    print(self.GuGuTable[:,x-2:y-1])

  def printSelectDan(self): ## 3번 메뉴
    lis=np.array((list(map(int,input("몇단부터 몇단까지 번호 입력 (2~N의 숫자로 입력 ex)2 3 8 )").split()))))-2
    print(self.GuGuTable[:,lis]) #인덱스 어래이 인덱서


 # def printSelectDan(self): ## 3번 메뉴
  #  n=len(GuGuTable[0])+1
  #  lis=np.array((list(map(int,input("몇단부터 몇단까지 번호 입력 (2~9의 숫자로 입력 ex)2 3 8 )").split()))))-2
  #  print(self.GuGuTable[:,lis]) #인덱스 어래이 인덱서

    
# 1 2 3 4 5 

def main():
  n=int(input("n단까지 초기화"))
  startGuGu=GuGuDan(n)
  
  selectMenu=[None,
              startGuGu.printOneDan,
              startGuGu.printRangeDan,
              startGuGu.printSelectDan
              ] ##중요! 호출하지말고!
  data={"exitNum"      :   4,
        "endingMsg"    :  "다음에 다시 만나요",
        "menuInputMsg" : "메뉴 번호 입력 : "}

      
  while True:
    startGuGu.Menu()
    select=int(input( data["menuInputMsg"]  ))

    if select==data["exitNum"]:
      print(data["endingMsg"])
      break; 
    selectMenu[select]()

if __name__ == '__main__':
    main()
    

KeyboardInterrupt: ignored

In [ ]:
  data={"exitNum"      :   4,
        "endingMsg"    :  "다음에 다시 만나요",
        "menuInputMsg" : "메뉴 번호 입력 : "}

data["exitNum"]

4

In [ ]:
import numpy as np
a3N = np.array([[x] * 5 for x in range(3)]) #예제 연습
print(a3N)


[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]]
